---

- name: Print some debug information
  vars:
    msg: |
        OS_U: {{ OS_USERNAME }}
        OS_P: {{ OS_PASSWORD }}
        OS_AU: {{ OS_AUTH_URL }}
        OS_PN: {{ OS_PROJECT_NAME }}
        OS_UDN: {{ OS_USER_DOMAIN_NAME }}
        OS_PDN: {{ OS_PROJECT_DOMAIN_NAME }}
        OS_OIPA: {{ OS_IDENTITY_API_VERSION }}
  debug:
    msg: "{{ msg.split('\n') }}"
  tags: debug_info

- name: Deploy admin-server-port1
  os_port:
    state: present
    name: admin-server-port1
    network: admin
    security_groups: 779e6d20-b926-41e9-a2fa-5e7328ea526e
# RED    security_groups: d8d792eb-7472-427e-8a6d-20ce51747b61

- name: Deploy server1-port1
  os_port:
    state: present
    name: server1-port1
    network: private
    security_groups: 779e6d20-b926-41e9-a2fa-5e7328ea526e
# RED    security_groups: d8d792eb-7472-427e-8a6d-20ce51747b61

#- name: Deploy private-cluster-server2-port1
#  os_port:
#    state: present
#    name: private-cluster-server2-port1
#    network: private
#    security_groups: 779e6d20-b926-41e9-a2fa-5e7328ea526e
# RED    security_groups: d8d792eb-7472-427e-8a6d-20ce51747b61

- name: Deploy admin-server instance
  os_server:
    state: present
    name: admin-server
    image: "cirros"
    timeout: 800
    flavor: m1.tiny
    auto_ip: false
    nics: "port-name=admin-server-port1,v4-fixed-ip=172.26.4.11"
    key_name: admin_key

- name: Deploy server1 instance
  os_server:
    state: present
    name: server1
    image: "cirros"
    timeout: 800
    flavor: m1.tiny
    auto_ip: false
    nics: "port-name=private-cluster-server1-port1,1v4-fixed-ip=172.25.4.11"
    key_name: admin_key

#- name: Deploy private-cluster-server2 instance
#  os_server:
#    state: present
#    name: private-cluster-server2
#    image: "cirros"
#    timeout: 800
#    flavor: m1.tiny
#    auto_ip: false
#    nics: "port-name=private-cluster-server2-port1,1v4-fixed-ip=172.25.4.11"
#    key_name: admin_key
