---

- name: Print some debug information
  vars:
    msg: |
        OS_U: {{ OS_USERNAME }}
        OS_P: {{ OS_PASSWORD }}
        OS_AU: {{ OS_AUTH_URL }}
        OS_PN: {{ OS_PROJECT_NAME }}
        OS_UDN: {{ OS_USER_DOMAIN_NAME }}
        OS_PDN: {{ OS_PROJECT_DOMAIN_NAME }}
        OS_OIPA: {{ OS_IDENTITY_API_VERSION }}
  debug:
    msg: "{{ msg.split('\n') }}"
  tags: debug_info

- name: Deploy admin-server instance
  os_server:
    state: present
    name: admin-server
    image: "cirros"
    timeout: 800
    flavor: m1.tiny
    network: admin
    auto_ip: no

- name: Deploy private-cluster1 instance
  os_server:
    state: present
    name: private-cluster1
    image: "cirros"
    timeout: 800
    flavor: m1.tiny
    network: private
    auto_ip: no

- name: Deploy private-cluster2 instance
  os_server:
    state: present
    name: private-cluster2
    image: "cirros"
    timeout: 800
    flavor: m1.tiny
    network: private
    auto_ip: no
