---

- name: Print some debug information
  vars:
    msg: |
        OS_U: {{ OS_USERNAME }}
        OS_P: {{ OS_PASSWORD }}
        OS_AU: {{ OS_AUTH_URL }}
        OS_PN: {{ OS_PROJECT_NAME }}
        OS_UDN: {{ OS_USER_DOMAIN_NAME }}
        OS_PDN: {{ OS_PROJECT_DOMAIN_NAME }}
        OS_OIPA: {{ OS_IDENTITY_API_VERSION }}
  debug:
    msg: "{{ msg.split('\n') }}"
  tags: debug_info

- name: Recall subnet private
  os_subnet:
    state: absent
    name: private_subnet

- name: Recall network private
  os_network:
    state: absent
    name: private

- name: Recall subnet admin
  os_subnet:
    state: absent
    name: admin_subnet

- name: Recall network admin
  os_network:
    state: absent
    name: admin
