---

- name: Print some debug information
  vars:
    msg: |
        OS_U: {{ OS_USERNAME }}
        OS_P: {{ OS_PASSWORD }}
        OS_AU: {{ OS_AUTH_URL }}
        OS_PN: {{ OS_PROJECT_NAME }}
        OS_UDN: {{ OS_USER_DOMAIN_NAME }}
        OS_PDN: {{ OS_PROJECT_DOMAIN_NAME }}
        OS_OIPA: {{ OS_IDENTITY_API_VERSION }}
  debug:
    msg: "{{ msg.split('\n') }}"
  tags: debug_info

- name: remove subnet private
  os_subnet:
    state: absent
    name: private_subnet
  environment:
    OS_USERNAME: "{{ OS_USERNAME }}"
    OS_PASSWORD: "{{ OS_PASSWORD }}"
    OS_AUTH_URL: "{{ OS_AUTH_URL }}"
    PS1: "{{ PS1 }}"
    OS_PROJECT_NAME: "{{ OS_PROJECT_NAME }}"
    OS_USER_DOMAIN_NAME: "{{ OS_USER_DOMAIN_NAME }}"
    OS_PROJECT_DOMAIN_NAME: "{{ OS_PROJECT_DOMAIN_NAME }}"
    OS_IDENTITY_API_VERSION: "{{ OS_IDENTITY_API_VERSION }}"

- name: remove network private
  os_network:
    state: absent
    name: private
  environment:
    OS_USERNAME: "{{ OS_USERNAME }}"
    OS_PASSWORD: "{{ OS_PASSWORD }}"
    OS_AUTH_URL: "{{ OS_AUTH_URL }}"
    PS1: "{{ PS1 }}"
    OS_PROJECT_NAME: "{{ OS_PROJECT_NAME }}"
    OS_USER_DOMAIN_NAME: "{{ OS_USER_DOMAIN_NAME }}"
    OS_PROJECT_DOMAIN_NAME: "{{ OS_PROJECT_DOMAIN_NAME }}"
    OS_IDENTITY_API_VERSION: "{{ OS_IDENTITY_API_VERSION }}"

- name: remove subnet admin
  os_subnet:
    state: absent
    name: admin_subnet
  environment:
    OS_USERNAME: "{{ OS_USERNAME }}"
    OS_PASSWORD: "{{ OS_PASSWORD }}"
    OS_AUTH_URL: "{{ OS_AUTH_URL }}"
    PS1: "{{ PS1 }}"
    OS_PROJECT_NAME: "{{ OS_PROJECT_NAME }}"
    OS_USER_DOMAIN_NAME: "{{ OS_USER_DOMAIN_NAME }}"
    OS_PROJECT_DOMAIN_NAME: "{{ OS_PROJECT_DOMAIN_NAME }}"
    OS_IDENTITY_API_VERSION: "{{ OS_IDENTITY_API_VERSION }}"

- name: remove network admin
  os_network:
    state: absent
    name: admin
  environment:
    OS_USERNAME: "{{ OS_USERNAME }}"
    OS_PASSWORD: "{{ OS_PASSWORD }}"
    OS_AUTH_URL: "{{ OS_AUTH_URL }}"
    PS1: "{{ PS1 }}"
    OS_PROJECT_NAME: "{{ OS_PROJECT_NAME }}"
    OS_USER_DOMAIN_NAME: "{{ OS_USER_DOMAIN_NAME }}"
    OS_PROJECT_DOMAIN_NAME: "{{ OS_PROJECT_DOMAIN_NAME }}"
    OS_IDENTITY_API_VERSION: "{{ OS_IDENTITY_API_VERSION }}"
