---

- name: Deploy image on OpenStack
  hosts: openstack
  gather_facts: false
  tasks:
#    - name: test
#      copy:
#        content: "hello worldly inhabitants\n"      
#        dest: /tmp/testfile.txt 
#    - name: Source keystonerc_admin
#      shell: "source /home/ansible/keystonerc_admin"

    - name: Download tempest image
      get_url:
        url: "http://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-disk.img"
        dest: "/var/tmp/cirros-0.4.0.img"

    - name: Authenticate to the cloud and retrieve the service catalog
      os_auth:
        cloud: rax-dfw

    - name: Upload an image from local disk
      os_image:
        auth:
          auth_url: http://192.168.1.121:5000/v3
          username: admin
          password: 0684cd3be8964ef7
          project_name: admin
        name: cirros-0.4.0
        container_format: bare
        disk_format: qcow2
        state: present
        filename: /var/tmp/cirros-0.4.0-x86_64-disk.img
        kernel: cirros-0.4.0-vmlinuz
        ramdisk: cirros-0.4.0-initrd
        properties:
          cpu_arch: x86_64
          distro: ubuntu
