---

- name: Deploy image on OpenStack
  hosts: openstack
  gather_facts: false
  tasks:
    - name: test
      copy:
        content: "hello worldly inhabitants\n"      
        dest: /tmp/testfile.txt 

    - name: Upload an image from http
      os_image:
        auth:
          auth_url: http://192.168.1.121:5000/v3
          username: admin
          password: 0684cd3be8964ef7
          project_name: admin
        name: cirros
#        container_format: bare
#        disk_format: qcow2
#        state: present
#        filename: cirros-0.3.0-x86_64-disk.img
#        kernel: cirros-vmlinuz
#        ramdisk: cirros-initrd
#        properties:
#          cpu_arch: x86_64
#          distro: ubuntu
