---

- name: Recall loadbalancers
  hosts: packstack
  gather_facts: false
  become: false
  vars_files:
    - "group_vars/openstack"
  roles:
    - {role: recall_loadbalancers, tags: 'recall_loadbalancers'}
  environment:
    OS_USERNAME: "{{ OS_USERNAME }}"
    OS_PASSWORD: "{{ OS_PASSWORD }}"
    OS_AUTH_URL: "{{ OS_AUTH_URL }}"
    PS1: "{{ PS1 }}"
    OS_PROJECT_NAME: "{{ OS_PROJECT_NAME }}"
    OS_USER_DOMAIN_NAME: "{{ OS_USER_DOMAIN_NAME }}"
    OS_PROJECT_DOMAIN_NAME: "{{ OS_PROJECT_DOMAIN_NAME }}"
    OS_IDENTITY_API_VERSION: "{{ OS_IDENTITY_API_VERSION }}"
