---

- name: Dismantle networks
  hosts: openstack
  gather_facts: false
  become: false

  environment:
    OS_USERNAME: admin
    OS_PASSWORD: 0684cd3be8964ef7
    OS_AUTH_URL: "http://192.168.1.121:5000/v3"
    PS1: ='[\u@\h \W(keystone_admin)]\$ '
    OS_PROJECT_NAME: admin
    OS_USER_DOMAIN_NAME: Default
    OS_PROJECT_DOMAIN_NAME: Default
    OS_IDENTITY_API_VERSION: 3

  tasks:
  - name: remove a subnet
    os_subnet:
      state: absent
      name: private_subnet

  - name: remove a network
    os_network:
      state: absent
      name: private
