---

- name: Print some debug information
  vars:
    msg: |
        OS_U: {{ OS_USERNAME }}
        OS_P: {{ OS_PASSWORD }}
        OS_AU: {{ OS_AUTH_URL }}
        OS_PN: {{ OS_PROJECT_NAME }}
        OS_UDN: {{ OS_USER_DOMAIN_NAME }}
        OS_PDN: {{ OS_PROJECT_DOMAIN_NAME }}
        OS_OIPA: {{ OS_IDENTITY_API_VERSION }}
  debug:
    msg: "{{ msg.split('\n') }}"
  tags: debug_info

- name: Deploy loadbalancer1 instance
  os_loadbalancer:
    state: present
    name: loadbalancer1
    vip_subnet: private_subnet
    auto_public_ip: true
    public_network: public
    listeners: 
      - name: loadbalancer1_80
        protocol: TCP
        protocol_port: 80
        pool:
          name: loadbalancer1_80_pool
          protocol: TCP
          members:
            - name: private
