---

- name: Print some debug information
  vars:
    msg: |
        OS_U: {{ OS_USERNAME }}
        OS_P: {{ OS_PASSWORD }}
        OS_AU: {{ OS_AUTH_URL }}
        OS_PN: {{ OS_PROJECT_NAME }}
        OS_UDN: {{ OS_USER_DOMAIN_NAME }}
        OS_PDN: {{ OS_PROJECT_DOMAIN_NAME }}
        OS_OIPA: {{ OS_IDENTITY_API_VERSION }}
  debug:
    msg: "{{ msg.split('\n') }}"
  tags: debug_info

- name: Deploy loadbalancer1-port1
  os_port:
    state: present
    name: loadbalancer1-port1
    network: private
    security_groups: 779e6d20-b926-41e9-a2fa-5e7328ea526e

#- name: Deploy listener for loadbalancer1
#  os_listener:
#    endpoint_type: internal
#    state: present
#    name: loadbalancer1_80
#    loadbalancer: loadbalancer1
#    protocol: HTTP
#    protocol_port: 80

- name: Deploy loadbalancer1 instance
  os_loadbalancer:
    state: present
    name: loadbalancer1
    vip_port: loadbalancer1-port1
    interface: internal
    vip_network: private
    vip_address: 172.25.4.10
#    public_ip_address: 172.24.4.10
#    public_network: public
    listeners: 
      - name: loadbalancer1_80
        protocol: TCP
        protocol_port: 80
        pool:
          name: loadbalancer1_80_pool
          protocol: TCP
          members:
            - name: private-cluster-server1
              address: 172.25.4.11
              protocol_port: 80
              subnet: private_subnet
            - name: private-cluster-server2
              address: 172.25.4.12
              protocol_port: 80
              subnet: private_subnet
    wait: true
    timeout: 800
