---

- name: create a private network
  os_network:
    state: present
    name: private

- name: create a private subnet
  os_subnet:
    state: present
    network_name: private
    name: private_subnet
    cidr: 172.25.4.0/24
