---

- name: Print some debug information
  vars: 
    msg: |
        OS_U: {{ OS_USERNAME }}
        OS_P: {{ OS_PASSWORD }}
        OS_AU: {{ OS_AUTH_URL }}
        OS_PN: {{ OS_PROJECT_NAME }}
        OS_UDN: {{ OS_USER_DOMAIN_NAME }}
        OS_PDN: {{ OS_PROJECT_DOMAIN_NAME }}
        OS_OIPA: {{ OS_IDENTITY_API_VERSION }}
  debug: 
    msg: "{{ msg.split('\n') }}"       
  tags: debug_info

- name: Create external router/gateway to connectprivate and admin network
  os_router:
    state: present
    name: router1
    network: public
    external_fixed_ips:
      - subnet: public_subnet
        ip: 172.24.4.250      
    interfaces:
      - net: private
        subnet: private_subnet
        portip: 172.25.4.250
      - net: admin
        subnet: admin_subnet
        portip: 172.26.4.250
