---

- name: Print some debug information
  vars: 
    msg: |
        OS_U: {{ OS_USERNAME }}
        OS_P: {{ OS_PASSWORD }}
        OS_AU: {{ OS_AUTH_URL }}
        OS_PN: {{ OS_PROJECT_NAME }}
        OS_UDN: {{ OS_USER_DOMAIN_NAME }}
        OS_PDN: {{ OS_PROJECT_DOMAIN_NAME }}
        OS_OIPA: {{ OS_IDENTITY_API_VERSION }}
  debug: 
    msg: "{{ msg.split('\n') }}"       
  tags: debug_info

- name: create a private network
  os_network:
    state: present
    name: private

- name: create a private subnet
  os_subnet:
    state: present
    network_name: private
    name: private_subnet
    cidr: 172.25.4.0/24

- name: create an admin network
  os_network:
    state: present
    name: admin

- name: create an admin subnet
  os_subnet:
    state: present
    network_name: admin
    name: admin_subnet
    cidr: 172.26.4.0/24
