---

- name: Print some debug information
  vars:
    msg: |
        OS_U: {{ OS_USERNAME }}
        OS_P: {{ OS_PASSWORD }}
        OS_AU: {{ OS_AUTH_URL }}
        OS_PN: {{ OS_PROJECT_NAME }}
        OS_UDN: {{ OS_USER_DOMAIN_NAME }}
        OS_PDN: {{ OS_PROJECT_DOMAIN_NAME }}
        OS_OIPA: {{ OS_IDENTITY_API_VERSION }}
  debug:
    msg: "{{ msg.split('\n') }}"
  tags: debug_info

- name: Recall server1 instance
  os_server:
    state: absent
    name: server1

#- name: Recall server2 instance
#  os_server:
#    state: absent
#    name: server2

- name: Recall admin-server instance
  os_server:
    state: absent
    name: admin-server

- name: Recall admin-server-port1
  os_port:
    state: absent
    name: admin-server-port1

- name: Recall server1-port1
  os_port:
    state: absent
    name: server1-port1

#- name: server2-port1
#  os_port:
#    state: absent
#    name: server2-port1
