---

- name: Print some debug information
  vars: 
    msg: |
        OS_U: {{ OS_USERNAME }}
        OS_P: {{ OS_PASSWORD }}
        OS_AU: {{ OS_AUTH_URL }}
        OS_PN: {{ OS_PROJECT_NAME }}
        OS_UDN: {{ OS_USER_DOMAIN_NAME }}
        OS_PDN: {{ OS_PROJECT_DOMAIN_NAME }}
        OS_OIPA: {{ OS_IDENTITY_API_VERSION }}
  debug: 
    msg: "{{ msg.split('\n') }}"       
  tags: debug_info

- name: Ensure unzip is present
  yum:
    name: unzip
    state: present

- name: Ensure tar is present
  yum:
    name: tar
    state: present

- name: Download image from CentOS server
  get_url:
    url: http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1901.qcow2.xz
    dest: /var/tmp/CentOS-7-x86_64-GenericCloud-1901.qcow2.xz

- name: Extract image
  unarchive:
    src: /var/tmp/CentOS-7-x86_64-GenericCloud-1901.qcow2.xz
    dest: /var/tmp/
    remote_src: yes

#- os_image:
#    auth:
#      auth_url: https://identity.example.com
#      username: admin
#      password: passme
#      project_name: admin
#      os_user_domain_name: Default
#      os_project_domain_name: Default
#    name: cirros
#    container_format: bare
#    disk_format: qcow2
#    state: present
#    filename: cirros-0.3.0-x86_64-disk.img
#    kernel: cirros-vmlinuz
#    ramdisk: cirros-initrd
#    properties:
#      cpu_arch: x86_64
#      distro: ubuntu
#
# VM image URL 
#http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1901.qcow2.xz
